//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class ChiTietHDN
    {
        public int MAHDN { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> GIANHAP { get; set; }

        [XmlIgnore]
        [JsonIgnore]
        public virtual HoaDonNhap HoaDonNhap { get; set; }
        [XmlIgnore]
        [JsonIgnore]
        public virtual Sanpham1 Sanpham1 { get; set; }
    }
}
