//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int ID { get; set; }
        public string TENSP { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string IMAGE { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    }
}
