//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Api.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using System.Xml.Serialization;

    public partial class HoaDonNhap
    {
        public int ID { get; set; }
        public Nullable<int> MANCC { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<double> THANHTIEN { get; set; }

        [XmlIgnore]
        [JsonIgnore]
        public virtual ChiTietHDN ChiTietHDN { get; set; }

        [XmlIgnore]
        [JsonIgnore]
        public virtual NhaCungCap NhaCungCap { get; set; }

        [XmlIgnore]
        [JsonIgnore]
        public virtual NhanVien NhanVien { get; set; }
    }
}
