//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class HoaDonXuat
    {
       
        public int ID { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        [XmlIgnore]
        [JsonIgnore]
        public virtual ChiTietHDX ChiTietHDX { get; set; }

        [XmlIgnore]
        [JsonIgnore]
        public virtual KhachHang KhachHang { get; set; }

        [XmlIgnore]
        [JsonIgnore]
        public virtual NhanVien NhanVien { get; set; }

        
    }
}
