//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;


    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDonNhap = new HashSet<HoaDonNhap>();
            this.HoaDonXuat = new HashSet<HoaDonXuat>();
        }

        public int ID { get; set; }
        public string TENNV { get; set; }
        public string CHUCVU { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> SODIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string TENTK { get; set; }
        public string MK { get; set; }

        [XmlIgnore]
        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonNhap> HoaDonNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [XmlIgnore]
        [JsonIgnore]
        public virtual ICollection<HoaDonXuat> HoaDonXuat { get; set; }
    }
}
