//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_Api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Sanpham1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham1()
        {
            this.ChiTietHDN = new HashSet<ChiTietHDN>();
            this.ChiTietHDX = new HashSet<ChiTietHDX>();

        }
    
        public int ID { get; set; }
        public string TENSP { get; set; }   
        public string IMAGE { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public string XUATXU { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string Description { get; set; }

        [XmlIgnore]
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDN> ChiTietHDN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore]
        [JsonIgnore]
        public virtual ICollection<ChiTietHDX> ChiTietHDX { get; set; }
        [XmlIgnore]
        [JsonIgnore]
        public virtual LoaiSanPham LoaiSanPham { get; set; }
     
       
    }
}
